name: haptic_x
description: "Very-very WIP package to work with CoreHaptics"
repository: https://github.com/rIIh/haptic_x
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  pigeon: ^24.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: HapticXPlugin
